apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-info-api-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-info-api
  targetCPUUtilizationPercentage: 50